[package]
name = "xds-test-util"
edition = "2024"
rust-version.workspace = true
homepage = "https://github.com/grpc/grpc-rust"
repository = "https://github.com/grpc/grpc-rust"
description = """
Test utilities for gRPC xDS implementations.
"""
keywords = ["grpc", "xds", "test"]
license = "MIT"
publish = false

[lints]
workspace = true

[dependencies]
envoy-types = "0.7"
prost = "0.14"
tonic = { version = "0.14", features = ["server"] }
tokio = { version = "1", features = ["sync", "rt", "net"] }
tokio-stream = { version = "0.1", features = ["net"] }
strum = { version = "0.28.0", features = ["derive"] }
tracing = "0.1.44"
